// SPDX-License-Identifier: MIT OR Apache-2.0
pragma solidity >=0.8.20;

/// GENERATED by tpt-axiom's onchain_export example from the arkworks
/// verifying key of `prove_balance_transfer`. Do not edit by hand; run the
/// exporter again when the circuit changes.
///
/// Groth16 verification over BLS12-381 through the EIP-2537 precompiles
/// (live on Ethereum mainnet since Pectra, May 2025). The pairing
/// precompile performs the subgroup checks.
///
/// Wire format (EIP-2537): field elements are 64 big-endian bytes, G1
/// points are 128 bytes (`x || y`), G2 points are 256 bytes
/// (`x.c0 || x.c1 || y.c0 || y.c1`). Coordinates exceed `uint256`, so the
/// interface is bytes-based.
///
/// Security note: Groth16 has a per-circuit trusted setup. This contract is
/// only as trustworthy as the ceremony behind the hardcoded verifying key —
/// see the repository's SECURITY.md.
contract Groth16Verifier {
    // BLS12-381 base field modulus (381 bits) as three 128-bit chunks.
    uint256 constant CHUNK0 = 0x1eabfffeb153ffffb9feffffffffaaab;
    uint256 constant CHUNK1 = 0x64774b84f38512bf6730d2a0f6b0f624;
    uint256 constant CHUNK2 = 0x1a0111ea397fe69a4b1ba7b6434bacd7;
    uint256 constant CHUNK_MASK = 0xffffffffffffffffffffffffffffffff;
    address constant G1_ADD = address(0x0b);
    address constant G1_MUL = address(0x0c);
    address constant PAIRING = address(0x0f); // EIP-2537 pairing check

    // ---- verifying key (hardcoded) --------------------------------------
    bytes constant IC_0 = hex"0000000000000000000000000000000008703bc6f1b5daed304a2c6840c67dac22c5c7e92d953bd466a8befd128a4f8aab77ce1a53fd04491b63abb1bb5fbc4b00000000000000000000000000000000129b650b160fdeae9c132f1021740b93098c98861a7b867a9d3fd518c426ecf86ff8e50e066d68bf51fce86d11cb5b52";
    bytes constant IC_1 = hex"000000000000000000000000000000000d5ec4006b5ad8cf616835657dfbe2056735b2e5b19e753329999a9d591b83e6acbc07df8c65a1c2c8588825c521c2d10000000000000000000000000000000013a5f9a4ac08b56c7e4d64515552430caceffb79bf86ed43973fec26e934fb1377652a8355a934a7669d15067f67fb03";
    bytes constant IC_2 = hex"0000000000000000000000000000000005e005083099f0a26b95c7511d39ca0c6ade383c8f34cae783dfe7de4acedd7d379181e690b77370ff03068628d01d910000000000000000000000000000000012e4d87e21d645566f1f1cd99d09abae79de67f195e2079d1ebfe2bc1bb1119e2666635c504c54e2891f36e0154d8463";

    bytes constant ALPHA = hex"0000000000000000000000000000000014547b208f2e190577af8b9f006cecd57917a4bc614955c812cc0bcc0c93ad1e8164b0d893dbb6f5e9f429a60706b0cf000000000000000000000000000000000caba4d962400c9e82ceb17301a43a62327ea75f75c1b1e497c21bd7172d9717d202038d1060a5545ad41f8c0d6d65dd";
    bytes constant BETA = hex"00000000000000000000000000000000142b8a3b98d386a9ce7169293661d905352ba3b64a3317664096b5f64ab3c23b985c24610b6a03539c0a79702fac53dc000000000000000000000000000000001348b9d2b531ba570313a8039ac71277dac181f9a9e65f99286a11da07f3b3efa07b27fc846e08f1170faa7a88935c9d00000000000000000000000000000000151def9b964c55bd1cdbef233059df56106ba48fd7163b23ac0e4858514c34f8c3a0aa0c5b480e9baa5ac0c464271019000000000000000000000000000000000c9f79f3f33baf80e1918a0d6ad5d3dd8614de6c11c06fea498357fbdf4be8f39f8e6419a7efa404d44dcefa9484d5d6";
    bytes constant GAMMA = hex"000000000000000000000000000000000c5dcba69c3bd22e2615499791eda3ac240d4e40067f3dec1ae8dbd706c50f3d4b4be33fbf2ebe115a4c3300aa87761a00000000000000000000000000000000086a4359e5e8fa7dedba72873d71b1693231b73b762c551f2acc3d9ed76395b84c990e3631b8eb00e0fcab27418ddb7f000000000000000000000000000000001300e59b109b502432ebfcf881cee272e169c65b8389fa761fe53df86a58f6241a8e251c1715cc83843574bfaac64d95000000000000000000000000000000000f40269813f39ff8758e3bf869d642ee0004f8d6249e5f27ff078ef698a0d7a2ac124a7e64d966229b798678356c46f8";
    bytes constant DELTA = hex"000000000000000000000000000000000b56d220208de63ce5227ae8ebe5b51666f2100ae491182456b0b3e28ee7dbb5be11a6b67c861fa89c7c68cf4dfe50b300000000000000000000000000000000140c17bc5150db9b3092284f6e9d0f552a1f0035a4433994c3a301847fd8e506f72a47dfd8c668361ef2d7cc715d15300000000000000000000000000000000004ab19052fe145ecfb45ac9bb71f51cc25dd00a650c9a474c368b03bb680872bd95e62cf0b9fc370f3ffa14283ae3c1e0000000000000000000000000000000013ad6b0fba2ef9d4a89f351424b25c84dc6ddab6080ab5e57b4c8b9f21348ab4247c466fed054b1406ecfb74fb959d14";

    function g1_add(bytes memory p, bytes memory q)
        internal view returns (bytes memory)
    {
        (bool ok, bytes memory out) = G1_ADD.staticcall(abi.encodePacked(p, q));
        require(ok && out.length == 128, "g1 add failed");
        return out;
    }

    function g1_mul(bytes memory p, uint256 s)
        internal view returns (bytes memory)
    {
        (bool ok, bytes memory out) =
            G1_MUL.staticcall(abi.encodePacked(p, bytes32(s))); // MSM: point, then scalar
        require(ok && out.length == 128, "g1 mul failed");
        return out;
    }

    /// Negates a G1 point: (x, y) -> (x, p - y), with p and y split into
    /// three 128-bit chunks (p is 381 bits = 3 x 128). The identity (all
    /// zeros) negates to itself.
    function g1_negate(bytes memory p) internal pure returns (bytes memory) {
        require(p.length == 128, "g1 point must be 128 bytes");
        bytes32 xHi;
        bytes32 xLo;
        bytes32 yHi;
        bytes32 yLo;
        assembly {
            xHi := mload(add(p, 32))
            xLo := mload(add(p, 64))
            yHi := mload(add(p, 96))
            yLo := mload(add(p, 128))
        }
        if (yHi == bytes32(0) && yLo == bytes32(0)) {
            return p; // the identity
        }
        unchecked {
            // y = yc2·2^256 + yc1·2^128 + yc0; p = pc2·2^256 + pc1·2^128 + pc0.
            uint256 yc0 = uint256(yLo) & CHUNK_MASK;
            uint256 yc1 = uint256(yLo) >> 128;
            uint256 yc2 = uint256(yHi);
            bool borrow = yc0 > CHUNK0;
            uint256 d0 = CHUNK0 - yc0;
            bool b1 = yc1 > CHUNK1 || (yc1 == CHUNK1 && borrow);
            uint256 d1 = CHUNK1 - yc1 - (borrow ? 1 : 0);
            bool b2 = yc2 > CHUNK2 || (yc2 == CHUNK2 && b1);
            uint256 d2 = CHUNK2 - yc2 - (b1 ? 1 : 0);
            require(!b2, "negation underflow (y >= p)");
            // Reassemble the 64-byte coordinate: the y field is
            // [16 zero bytes | d2 | d1 | d0] (p < 2^381, d2 < 2^125).
            return abi.encodePacked(
                xHi,
                xLo,
                bytes16(0),
                bytes16(uint128(d2)),
                bytes16(uint128(d1)),
                bytes16(uint128(d0))
            );
        }
    }

    /// DEBUG: the exact bytes handed to the pairing precompile (used by the
    /// generated test to diff the Solidity construction against the Rust
    /// construction byte for byte).
    function debugPairingInput(
        bytes calldata a,
        bytes calldata b,
        bytes calldata c,
        uint256[2] calldata publics
    ) public view returns (bytes memory) {
        require(a.length == 128 && b.length == 256 && c.length == 128, "bad encoding");
        bytes memory vkx = IC_0;
        vkx = g1_add(vkx, g1_mul(IC_1, publics[1 - 1]));
        vkx = g1_add(vkx, g1_mul(IC_2, publics[2 - 1]));

        bytes memory negA = g1_negate(a);
        return abi.encodePacked(
            negA, b,
            ALPHA, BETA,
            vkx, GAMMA,
            c, DELTA
        );
    }

    /// Groth16: e(-A, B) · e(alpha, beta) · e(vk_x, gamma) · e(C, delta) == 1,
    /// where vk_x = IC_0 + Σ pub_i · IC_i.
    function verifyProof(
        bytes calldata a, // 128-byte G1 point
        bytes calldata b, // 256-byte G2 point
        bytes calldata c, // 128-byte G1 point
        uint256[2] calldata publics
    ) public view returns (bool) {
        require(a.length == 128 && b.length == 256 && c.length == 128, "bad encoding");
        bytes memory vkx = IC_0;
        vkx = g1_add(vkx, g1_mul(IC_1, publics[1 - 1]));
        vkx = g1_add(vkx, g1_mul(IC_2, publics[2 - 1]));

        bytes memory negA = g1_negate(a);

        bytes memory input = abi.encodePacked(
            negA, b,
            ALPHA, BETA,
            vkx, GAMMA,
            c, DELTA
        );
        (bool callOk, bytes memory out) = PAIRING.staticcall(input);
        return callOk && out.length == 32 && abi.decode(out, (uint256)) == 1;
    }
}
