[package]
name = "tpt-axiom"
description = "Probabilistic logic and native zero-knowledge state for Rust"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
axiom-core = { workspace = true }
axiom-ir = { workspace = true }
axiom-macros = { workspace = true }
axiom-zk = { workspace = true }